### ISSUE TITLE
find total is always zero when raw is false

### ISSUE THREAD

**Issue by bichenkk** [feathersjs/feathers-sequelize#118]
### Steps to reproduce
I have a 3 models. Product, Shop and Branch.
- A product only belongs to a shop.
- A shop has many branches.

I am trying to add this in the find before hook

`
const sequelize = hook.app.get('sequelizeClient');
`
`
hook.params.sequelize = {
    raw: false,
    include: [
      sequelize.models.shops,
      {
        model: sequelize.models['branch-products'],
        include: [{ model: sequelize.models.branches}]
      }
    ]
  };
`

### Actual behavior

When I add the raw: false, the total is always 0.
Also, when I add where in the query. It gives repeated objects.

**Comment by advanwinkel** [comment]
I had a similar problem using Sequelize 4.x with a model having an association and I did some research.

I have a model 'products' with a belongsToMany association to 'categories'. When I do a find including categories without `raw: false` in the options I get repeated objects, like
```
{
  "data": [
    {
      "id": 43900,
      "name": ..,
      "type": ...,

      "categories.id": "abcat0208002",
      "categories.name": ...",
      "categories.createdAt": ...,
      "categories.updatedAt": ...,
 
    },
    {
	"id": 43900,
	"name": ...

	...
```
This is clearly not what we want.
When I put `raw: false in the options I get the correct Jason, like
```
{
  "data": [
    {
      "id": 43900,
      "name": ...,
      "type": ...,
      "price": 5.49,
 
      "categories": [
        {
          "id": "abcat0208002",
          "name": ...,
          "createdAt": ...,
          "updatedAt": ...,

        },
        {
          "id": "pcmcat248700050021",
          "name": ...,
          "createdAt": ...,
          "updatedAt": ..."
        },
```
However now total is 0.
I found out that this problem is caused by a particular behaviour, probably a bug, in Sequelize 4.x.
Feather's find method is calling Sequelize's method `Model.findAndCount()`.
This function is working only correctly for models with associations, when there is no raw parameter in the options.
However Feathers-sequelize puts the raw parameter to a default value `true`, which leads to a result with repeated objects.
If we override raw with `raw: false` the data has the right format, but count becomes 0.

This problem can only be solved either by changing the behaviour of `findAndCount` in Sequelize, or by no longer enforcing `raw: true` as a default for method `find` in Feathers-sequelize.

For the moment I have devised a workaround by adding `raw: false` to options in the find-before hook and adding a find-after hook in which I call `Model.count` in Sequelize, like this:

```
after: {
    all: [],
    find: [countRows],


function countRows (hook) {
  return new Promise((resolve, reject) => {
          hook.service.Model.count().then(function (result) {
	        hook.result.total = result;
	        resolve(hook);
        });
   });
}
```
Now `countRows()` sets total to the correct value.

**Comment by YeFFreY** [comment]
@bichenkk I had the same issue, Sequelize is using the options "raw:false" you give to perform also the "count" which returns an "entity" instead of a plain javascript object.
This entity is not processed correctly by Sequelize because it expects a plain object... 

The solution I use is to just add a sequelize "beforeCount" hook in your sequelize model :
`
hooks: {
  beforeCount: (options) => {
    options.raw = true;
  }
},
`

So the "raw" options will be correct for the "count" query and you get the total number of rows.

**Comment by advanwinkel** [comment]
**@YeFFreY**  Thanks, this is way better than my workaround! I didn't know about hooks in Sequelize.
Still I don't understand why Sequelize doesn't give the right result with `raw: true` and we have to override the default raw option of Feathers.

**Comment by bichenkk** [comment]
@YeFFreY Thanks a lot! I guess this should be more well documented. I have changed the find query to pure mySQL because of this issue.

**Comment by adrianolsk** [comment]
I have the exact same problem, I use ```raw=false``` because I want to retrieve associations and it gives me a object with the properties from the other model.
If I use raw true it would return ugly data like `invoice.customer.name` that I cant only access cliente site by use the property as a index `invoice['customer.name']`
I end up let raw=true and creating a after hook to loop through the data and assing the `customer.name` to a property ```customer_name``` so I can use ```invoice.customer_name```

**Comment by daffl** [comment]
I added the hook by default to a generated Sequelize model in https://github.com/feathersjs/generator-feathers/pull/238
