### ISSUE TITLE
use inside php server

### ISSUE THREAD

**Issue by vahidalvandi** [feathersjs/feathers-sequelize#151]
i will build simple to do list with real time database . i have backend build with php laravel . 
how i can use feathersjs with php with rest .?

**Comment by daffl** [comment]
This is a very broad question (and not really Sequelize related) but I'll try and give some pointers.

First, I'd go through the [guides](https://docs.feathersjs.com/guides/readme.html) to get an idea what Feathers does and how it works. 

How to use Feathers through REST directly is documented in the [REST direct connection API](https://docs.feathersjs.com/api/rest.html#direct-connection). Keep in mind though, that REST does not provide real-time functionality. In order to get real-time functionality clients have to connect to the Feathers Socket.io server.

You could also use the Feathers server as a [real-time proxy](https://blog.feathersjs.com/using-feathersjs-to-make-your-existing-api-real-time-813f7c3fd892) for your existing API and then implement the todo list in that server.
