### ISSUE TITLE
Add a toJSON bundled hook like mongoose

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-sequelize#18]

**Comment by daffl** [comment]
I'm wondering if we should start the common hook colletion module right away and provide a `transform` hook that does something like

```
var transform = require('feathers-common-hooks/transform');

app.service('todos').after(transform('toJSON'));
app.service('todos').after(transform(function(data) {
 // Do something here
}));
```

Which in the first case will call `hook.result.toJSON` and in the second run the function.

**Comment by ekryski** [comment]
Ya I'm liking that idea. Especially because we have to handle arrays and pagination sometimes I can see that as a potential pitfall if people have to implement the hooks themselves.

**Comment by ekryski** [comment]
No longer required as of v2.0.0 since it returns regular JS objects by default.

**Comment by zusamann** [comment]
I think this is still required. 

I have use case of few related models. Upon using `include`, by default the values returned are firstly flattened out: 
```json
{
   "role.roleId": "".
   "role.name": ""
}
```
instead of
```json
{
  "role": {
    "roleId": "",
    "name": ""
  }
}
```
Just this would've been fine as it'd be easy to convert the first result to second. But the issue comes when the included results are an array, in which case the above result doesn't contain all values, just one.

So there is no option but to use `{ raw: false }` on the models. Which ofcourse breaks hooks like `discard` `remove` and many more I imagine.

**Comment by zusamann** [comment]
Though of course a very simple solution exists:
```js
all: [
  hook => ({
    ...hook,
    result: hook.result.toJSON()
  }),
  discard('password')
]
```
But I'd say a transform hook is still a good idea, because the explicit presence of it in the docs will really help people.

**Comment by eikaramba** [comment]
I just updated my dependencies and now my results are also flattened. Why is that the case? That does not make sense for me.
