### ISSUE TITLE
Add `lean` attribute to automatically call toJSON?

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-sequelize#19]
This isn't officially an attribute in sequelize but it's pretty handy for `feathers-mongoose` I'm wondering if we should implement it here as well.

**Comment by kulakowka** [comment]
I'm sure that this must be done

**Comment by petermikitsh** [comment]
Consistent results would really be nice. You really want to avoid the ORM objects at all times, if possible. Here's what I've been doing as a stop gap solution...

```js
app.hooks({
  after(hook) {
    if (hook.method === 'create' && typeof _.get(hook, 'result.toJSON') === 'function') {
      hook.result = hook.result.toJSON();
    }
  }
});
```

One side effect I recently encountered was that, in my service `filter` functions, I'd have to inspect to see whether or not the first parameter (`data`) was a sequelize DAO or a plain, javascript object. This is because create (by default) returns a DAO, while all other service methods will return POJO's when you add `query: {raw: true}` to your sequelize connection object (more on that [here](https://github.com/feathersjs/feathers-sequelize/issues/24#issuecomment-242511627)). This filter solves the need for that check.

But yeah, avoiding the ORM-specific logic inside of service code is, imo, a good direction for this adapter.

**Comment by eddyystop** [comment]
Bump.

**Comment by MichaelErmer** [comment]
This would be good, it would save a lot of extra calls in hooks like:
```
      // If it's a mongoose model then
      if (typeof obj.toObject === 'function') {
        obj = obj.toObject(); 
      }
      // If it's a Sequelize model   
      else if (typeof obj.toJSON === 'function') {
        obj = obj.toJSON();
      }
```

**Comment by ekryski** [comment]
The attribute has been changed to `raw: true` by default. v2.0.0 now returns regular JavaScript objects by default and there are hooks to covert to and from Sequelize models. See #106 for more info.
